# Generated by Django 5.0.2 on 2025-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='album_images'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='song_images'),
        ),
    ]
