# Generated by Django 5.0.2 on 2025-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_image_alter_songs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='music.songs'),
        ),
    ]
